services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    healthcheck:
        test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WP_REDIS_HOST=redis
      - WP_REDIS_SCHEMA=tcp
  redis:
    image: wodby/redis:6
  wpcli:
    depends_on:
      wordpress:
        condition: service_started
      db:
        condition: service_healthy
    image: wordpress:cli
    user: 33:33
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WP_REDIS_HOST=redis
      - WP_REDIS_SCHEMA=tcp
    links:
      - db:db
    entrypoint: sleep
    command: "3600"
    volumes:
      - wp_data:/var/www/html
    working_dir: /var/www/html
  infinispan:
    image: quay.io/infinispan/server:15.0.3.Final
    volumes:
      - ./infinispan:/opt/infinispan/infinispan
    command: -s infinispan -c infinispan-resp.xml
volumes:
  db_data:
  wp_data:
